name: Hello world Workflow

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
    workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "HELLO WORLD"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "GOODBYE WORLD"
        shell: bash     